/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mutlu.advent


import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {
    @Test
    fun `I am trying to test`() {


        assertThat("a").isEqualTo("a")
    }
}
