/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mutlu.advent.day2


import org.assertj.core.api.Assertions.assertThat
import java.io.File
import kotlin.test.Test

class AppTest {

}
