/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mutlu.advent.day1


import org.assertj.core.api.Assertions.assertThat
import java.io.File
import kotlin.test.Test

class AppTest {
    @Test
    fun `calculate fuel when a mass is given`() {
        val fuel = App().calculateFuel(100756)
        assertThat(fuel).isEqualTo(33583)
    }

    @Test
    fun `calculate total fuel when all module is given`() {
        val arrayOfString = File(ClassLoader.getSystemResource("TestData01.txt").file).readLines()
        val list = arrayOfString.filterNot {
            it.isBlank()
        }.map {
            it.toInt()
        }
        val totalFuel = list.let { App().calculateTotalFuel(it) }

        assertThat(totalFuel).isEqualTo(656)
    }
}
