/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mutlu.advent.day1

class App {
    fun calculateFuel(mass: Int): Int {
        return (mass / 3) - 2
    }

    fun calculateTotalFuel(listOfModules: List<Int>): Int {
        return listOfModules
            .map { calculateFuel(it) }
            .reduce { acc, i ->
                acc + i
            }
    }
}

